name = "PIQL"
uuid = "bbcca2e2-8668-413d-ba81-c82c0d64d1df"
authors = ["chelate <42802644+chelate@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
